- hosts: 127.0.0.1
  vars:
    version: ce-20200201
    directory: sip3-backend
  roles:
    - { role: ../../roles/host-file-system, tags: host-file-system }
    - { role: ../../roles/docker-network, tags: docker-network }
    - { role: ../../roles/grafana, tags: grafana }
    - { role: ../../roles/influxdb, tags: influxdb }
    - { role: ../../roles/mongodb, tags: mongodb }
    - { role: ../../roles/sip3-salto, tags: sip3-salto }
    - { role: ../../roles/sip3-twig, tags: sip3-twig }
    - { role: ../../roles/sip3-hoof, tags: sip3-hoof }