- hosts: 127.0.0.1
  vars:
    version: ce-20200317
    directory: sip3-captain
  roles:
    - { role: ../../roles/host-file-system, tags: host-file-system }
    - { role: ../../roles/sip3-captain, tags: sip3-captain }